
version: '2'

services:
   
    mongo:
        image: mongo:latest
        container_name: mongo
        ports: 
            - "27017:27017"
            
    mysql:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - "3306:3306"
        
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: k8suser
            MYSQL_PASSWORD: k8suser
            MYSQL_DATABASE: k8sdb 
    
    django-app-service:
        image: colvet/djangotest:latest
        container_name: django-app-service
        ports: 
            - "8083:8083"
        volumes: 
            - /로컬 파일 저장 위치:/usr/src/app/data
        depends_on: 
            - mysql
            - mongo
    
    login-app-service:
        image: colvet/login-app-service:latest
        container_name: login-app-service
        ports: 
            - "8087:8087"
        depends_on: 
            - mysql
            - mongo
        volumes: 
            - /로컬 파일 저장 위치:/data
    dei-service:
        image: wlgns0719/dei-service:latest
        container_name: dei-service
        ports: 
            - "8085:8085"
        volumes: 
            - /로컬 파일 저장 위치:/data
        depends_on: 
            - mysql
            - mongo
